### ISSUE TITLE
Allowing custom methods

### ISSUE THREAD

**Issue by kirpachov** [spokesoftware/limeade#1]
Hi. I'd like Limeade to allow me call custom methods, defined by me, on LimeSurvey API.
I am both LimeSurvey-end developer and Rails-end developer.
I've added a new endpoint to LimeSurvey remotecontrol, and would like the possibility to add call it with your gem.

Right now I'm re-defining Limeade::API_METHODS, but as you can imagine a get a warning in the console :-(

Let me know anything
Thanks
Sasha

**Comment by javmorin** [comment]
@OlecsandrKirpa Apologies for the slow response to your request. I have just pushed version 0.1.3 of `limeade` to rubygems which switches it from a const/method_missing based verification to a per-call api definition. 

You should now be able to define additional api calls by calling `Limeade::Client.define_api_method :<your rpc method>`. 

See the documentation and usage in [client.rb](https://github.com/spokesoftware/limeade/blob/master/lib/limeade/client.rb). Hope this helps you out!
